# fly.toml app configuration file generated for notehelper-api on 2026-06-22T16:32:54-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'notehelper-api'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  CHROMA_PERSIST_DIR = '/data/chroma_db'

[[mounts]]
  source = 'notehelper_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
